# Generated by Django 3.0.5 on 2021-08-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_browser',
            field=models.CharField(max_length=2000),
        ),
    ]
